### ISSUE TITLE
Unable to handle values with special characters

### ISSUE THREAD

**Issue by VeenitShah** [adamhajari/spyre#56]
I have a lot of dirty data with special characters. I want to be able to use a dropdown and select one value of it with contains a `#`. I modified the StockExample to the following - 

```
"options" : [ {"label": "Google", "value":"GOOG"},
                                  {"label": "Yahoo", "value":"YHOO"},
                                  {"label": "Apple", "value":"AAPL"},
                                  {"label": "Test", "value": "TESTVALUE#123"}]
```

When I select the Test label, I get the following stack trace - 

```
Traceback (most recent call last):
  File "/anaconda/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/anaconda/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/anaconda/lib/python2.7/site-packages/spyre/server.py", line 216, in table
    df = self.getTable(args)
  File "/anaconda/lib/python2.7/site-packages/spyre/server.py", line 327, in getTable
    df = self.getData(params)
  File "example.py", line 39, in getData
    data = json.loads(result.decode("utf8").replace('finance_charts_json_callback( ','')[:-1])  # strip away the javascript and load json
  File "/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 10 column 1 (char 217)
```

**Comment by adamhajari** [comment]
@VeenitShah i'm not able to reproduce. What version of spyre are you using? Have you tried putting 
```
# coding: utf-8
```
at the top of your script?

see: https://www.python.org/dev/peps/pep-0263/
